### ISSUE TITLE
The file hash-ladder-exp.txt missing.

### ISSUE THREAD

**Issue by vals** [khj3017/hash_ladder#1]
Hi, I can't locate the file `hash-ladder-exp.txt` which is read in the `code/flavopiridol/analyze_hash_table.R` script.

Has it been renamed and made available somewhere else?

Best,
/Valentine

**Comment by khj3017** [comment]
Hi,

Thanks for catching that. It looks like the hash-ladder-exp.txt file was
not included in the original submission. It is now added to the repository.

Best,
Hyeon-Jin

**Comment by vals** [comment]
Thank you!

/Valentine
